### PR TITLE
Fix embedded protobuf decoding

### PR DESCRIPTION
**Pull request by fuzzyrichie**
### Problem

While it is possible to decode a string and then, in the event it cannot be decoded, we fallback to a length-delimited byte string, I have found in my use that it is common to decode an embedded protobuf message incorrectly as a string. That is because shorter protobuf messages can usually decode well into a string over large string messages.

### Solution
The new approach is to do a string-decode first, and then use a count of unprintable characters (i.e. less than 0x20 in the ASCII table) to determine if we got it right or not. If there's more than 1 unprintable character in the first 4 characters, then we'll do a protobuf parsing instead. We distinguish that the first character of the string could be equal to 0x20, so we special-case the first character.

### CODE REVIEW

**Comment by fuzzyrichie** [comment]
Leave this with me for now - it needs some more work, I hit some unexpected edge cases!

**Comment by dannyhann** [comment]
Hello, @fuzzyrichie

Thank you so much for your feedback. I really appreciate your interest and contribution. 
I understand the issue you pointed out, and I admit, there can be similar issues in my recent improvements as well.

My project is focused on decoding protobuf binary messages with Python code, without proto files. I'm aware that distinguishing between LENGTH_DELIMITED as text or nested protobuf is not always straightforward.

I’m considering introducing a result object type that allows users to choose between the two cases (text/nested protobuf). For instance, providing to_text() and to_results() methods. Users can rely on to_text() if it returns a meaningful interpretation, and switch to to_results() in case of errors or corrupted binaries.

I'm also thinking about adding xpath or IDs to the parsing tree. This way, the person decoding can choose what they need.


Looking forward to your edge case improvements. Any further feedback or suggestions are always welcome.

Thank you.

**Comment by dannyhann** [comment]
@fuzzyrichie 
Wow, this is working code! 
It seems like you’ve found a pattern that can distinguish between the cases fairly accurately. 
Impressive! 👍

I have a question and a suggestion:

Are there any exception cases that cannot be addressed with `isprintable`?

Could you possibly improve the structure to inject or extend the distinguishing logic? Or maybe refactor the distinguishing logic into a separate method?

For instance:

``` python 
def has_valid_string(data) -> typing.Tuple[bool, str]:
    """Your distinguishing logic goes here"""

def _get_delimited_data_handler(self, chunck):
    ...
    data = list(map(lambda x: hex(x)[2:].zfill(2), self._buffer))
    string_or_not = " ".join(data)
    is_valid, _data = self.has_valid_string(string_or_not)
    if is_valid:
        wire_type = "string"
        data = _data
    else:
        sub_parsed_data = self._create_nested_parser().parse(string_or_not)
        data = sub_parsed_data
        wire_type = "length_delimited"
    ...
 ```
the code has become more stable.
Once again, thank you for your contribution!

**Comment by fuzzyrichie** [comment]
@dannyhann - sure! Let me take those changes over the weekend and test them, the proposed change is simple enough :)

**Pull request merged**
